-- ============================================
-- PHASE 4 — SYMBOL AUTHORITY MODEL
-- ============================================

CREATE TABLE IF NOT EXISTS symbol_whitelist (
    symbol TEXT PRIMARY KEY,
    market_mode TEXT NOT NULL CHECK (market_mode IN ('EQUITY','CRYPTO'))
);

-- Clear existing (optional but recommended on first deploy)
TRUNCATE TABLE symbol_whitelist;

-- =========================
-- EQUITY SYMBOLS
-- =========================
INSERT INTO symbol_whitelist (symbol, market_mode) VALUES
-- ETF HOLDINGS
('XOM','EQUITY'),('CVX','EQUITY'),('COP','EQUITY'),('WMB','EQUITY'),('MPC','EQUITY'),
('EOG','EQUITY'),('PSX','EQUITY'),('VLO','EQUITY'),('KMI','EQUITY'),('BKR','EQUITY'),
('NVDA','EQUITY'),('AAPL','EQUITY'),('MSFT','EQUITY'),('AVGO','EQUITY'),('PLTR','EQUITY'),
('AMD','EQUITY'),('ORCL','EQUITY'),('CSCO','EQUITY'),('IBM','EQUITY'),('MU','EQUITY'),
('GOOGL','EQUITY'),('GOOG','EQUITY'),('AMZN','EQUITY'),('TSLA','EQUITY'),('META','EQUITY'),
('LLY','EQUITY'),

-- SMALL WATCHLIST
('OPEN','EQUITY'),('TE','EQUITY'),('BFST','EQUITY'),('NB','EQUITY'),('SES','EQUITY'),
('SIDU','EQUITY'),('WDC','EQUITY'),('TSM','EQUITY'),('ARM','EQUITY'),('UEC','EQUITY'),
('UUUU','EQUITY'),('CCJ','EQUITY'),('SMCI','EQUITY'),('INTC','EQUITY'),('USAR','EQUITY'),
('LMT','EQUITY'),('ASTS','EQUITY'),('RVMD','EQUITY'),('STX','EQUITY'),

-- WATCHLIST
('IBIT','EQUITY'),('KRMN','EQUITY'),('LAR','EQUITY'),('XLF','EQUITY'),('BBAI','EQUITY'),
('LAC','EQUITY'),('MVST','EQUITY'),('ABAT','EQUITY'),('RGTI','EQUITY'),

-- AI/QUANTUM
('QUBT','EQUITY'),('QBTS','EQUITY'),('IONQ','EQUITY'),('AIQ','EQUITY'),
('ROBT','EQUITY'),('QTUM','EQUITY'),('NBIS','EQUITY'),('OKLO','EQUITY'),('CMCSA','EQUITY'),

-- BIG DOGS
('PKST','EQUITY'),('NFLX','EQUITY'),('F','EQUITY'),('GM','EQUITY'),('MSTR','EQUITY'),
('SOFI','EQUITY'),('COIN','EQUITY'),('BMNR','EQUITY'),('NVO','EQUITY'),

-- BIOTECH
('LPTH','EQUITY'),('ANIX','EQUITY'),('PED','EQUITY'),('XTLB','EQUITY'),
('ISD','EQUITY'),('TLRY','EQUITY'),('IONR','EQUITY'),

-- CAPITAL MARKETS
('HRZN','EQUITY'),('HTFC','EQUITY'),('OXSQ','EQUITY'),('PSEC','EQUITY'),
('FSK','EQUITY'),('OFS','EQUITY'),('WHF','EQUITY'),('WHFCL','EQUITY'),('ICMB','EQUITY'),

-- DIVIDENDS
('TSYY','EQUITY'),('ULTY','EQUITY'),('VYM','EQUITY'),('USOY','EQUITY'),
('O','EQUITY'),('MAIN','EQUITY'),('JEPI','EQUITY'),('FDVV','EQUITY'),
('FDHY','EQUITY'),('T','EQUITY'),('PFE','EQUITY'),('BAC','EQUITY'),('KO','EQUITY'),

-- ONE WISH
('OUST','EQUITY'),('DXYZ','EQUITY'),('BTE','EQUITY'),('TV','EQUITY'),('BORR','EQUITY'),
('EVEX','EQUITY'),('BB','EQUITY'),('AMC','EQUITY'),('CLVT','EQUITY'),('NXDR','EQUITY'),
('UA','EQUITY'),('UWMC','EQUITY'),('RIG','EQUITY'),

-- ROCKET SHIPS
('LZMH','EQUITY'),('SOPA','EQUITY'),('MAIA','EQUITY'),('SGLY','EQUITY'),
('SOC','EQUITY'),('HSDT','EQUITY'),('BNAI','EQUITY'),('JFBR','EQUITY'),
('PACB','EQUITY'),('DBGI','EQUITY'),('SMJF','EQUITY'),('NUAI','EQUITY'),
('LPCN','EQUITY'),('CANG','EQUITY'),('ITRM','EQUITY'),('RUBI','EQUITY'),
('ANGH','EQUITY'),('NCL','EQUITY'),('INBS','EQUITY'),('SLGB','EQUITY'),
('ALCY','EQUITY'),('VNDA','EQUITY'),('ORIS','EQUITY'),

-- ETFs & Commodities
('RING','EQUITY'),('GDMN','EQUITY'),('USO','EQUITY'),('SLV','EQUITY'),
('DBA','EQUITY'),('GOLY','EQUITY'),('XLE','EQUITY'),('NVDW','EQUITY'),
('NLY','EQUITY'),('AGNC','EQUITY'),('KBWY','EQUITY'),
('CWB','EQUITY'),('IWMY','EQUITY'),('NVYY','EQUITY'),('TQQY','EQUITY'),
('YMAG','EQUITY'),('YSPY','EQUITY'),('NVDY','EQUITY'),('DFAC','EQUITY'),
('DJCIGC','EQUITY'),
('VDE','EQUITY'),('VVGT','EQUITY'),('VMGK','EQUITY'),('VVONG','EQUITY');

-- =========================
-- CRYPTO SYMBOLS
-- =========================
INSERT INTO symbol_whitelist (symbol, market_mode) VALUES
('BTC/USD','CRYPTO'),('ETH/USD','CRYPTO'),('BNB/USD','CRYPTO'),('SOL/USD','CRYPTO'),
('ADA/USD','CRYPTO'),('AVAX/USD','CRYPTO'),('DOT/USD','CRYPTO'),('MATIC/USD','CRYPTO'),
('ATOM/USD','CRYPTO'),('NEAR/USD','CRYPTO'),('APT/USD','CRYPTO'),('SUI/USD','CRYPTO'),
('SEI/USD','CRYPTO'),('INJ/USD','CRYPTO'),('FTM/USD','CRYPTO'),('ALGO/USD','CRYPTO'),
('XTZ/USD','CRYPTO'),('EGLD/USD','CRYPTO'),('HBAR/USD','CRYPTO'),('TON/USD','CRYPTO'),
('ARB/USD','CRYPTO'),('OP/USD','CRYPTO'),('IMX/USD','CRYPTO'),('LRC/USD','CRYPTO'),
('METIS/USD','CRYPTO'),
('UNI/USD','CRYPTO'),('AAVE/USD','CRYPTO'),('LINK/USD','CRYPTO'),('MKR/USD','CRYPTO'),
('SNX/USD','CRYPTO'),('CRV/USD','CRYPTO'),('SUSHI/USD','CRYPTO'),('COMP/USD','CRYPTO'),
('BAL/USD','CRYPTO'),('1INCH/USD','CRYPTO'),('RUNE/USD','CRYPTO'),('DYDX/USD','CRYPTO'),
('GMX/USD','CRYPTO'),('PENDLE/USD','CRYPTO'),
('DOGE/USD','CRYPTO'),('SHIB/USD','CRYPTO'),('PEPE/USD','CRYPTO'),('FLOKI/USD','CRYPTO'),
('BONK/USD','CRYPTO'),('WIF/USD','CRYPTO'),
('FET/USD','CRYPTO'),('AGIX/USD','CRYPTO'),('OCEAN/USD','CRYPTO'),('RNDR/USD','CRYPTO'),
('GRT/USD','CRYPTO'),('TAO/USD','CRYPTO'),('AKT/USD','CRYPTO'),
('AXS/USD','CRYPTO'),('SAND/USD','CRYPTO'),('MANA/USD','CRYPTO'),('ENJ/USD','CRYPTO'),
('GALA/USD','CRYPTO'),('ILV/USD','CRYPTO'),('BLUR/USD','CRYPTO'),('MAGIC/USD','CRYPTO'),
('BEAM/USD','CRYPTO'),('PRIME/USD','CRYPTO'),
('FIL/USD','CRYPTO'),('AR/USD','CRYPTO'),('STX/USD','CRYPTO'),('ICP/USD','CRYPTO'),
('XMR/USD','CRYPTO'),('ZEC/USD','CRYPTO'),('CRO/USD','CRYPTO'),
('ONDO/USD','CRYPTO'),
('LDO/USD','CRYPTO'),('RPL/USD','CRYPTO'),
('TIA/USD','CRYPTO'),('WLD/USD','CRYPTO'),('STRK/USD','CRYPTO'),('JUP/USD','CRYPTO'),
('JTO/USD','CRYPTO'),('PYTH/USD','CRYPTO'),
('VET/USD','CRYPTO'),('XLM/USD','CRYPTO'),('TRX/USD','CRYPTO'),
('ETC/USD','CRYPTO'),('LTC/USD','CRYPTO'),('BCH/USD','CRYPTO'),('XRP/USD','CRYPTO');
